TypeScript 5.2.2 Support (#2466)
Previously, if you used tuple labels TypeScript required all members to
have a label. Otherwise, you'd get this error:
```
error TS5084: Tuple members must all have names or all not have names.
```

TypeScript 5.2 removed this requirement so now we have to check if
`label` exists before using it.